// packages/react/src/nodes/AccordionNode.tsx
import { GAP, RADIUS } from "@kivcode/nodes";
import { useContext, useEffect, useMemo, useRef, useState } from "react";
import { KivBusContext } from "../bus";
import type { KivNodeComponentProps } from "../node-props";
import {
	AccordionContext,
	type AccordionContextValue,
} from "./accordion-context";

declare module "@kivcode/engine" {
	interface KivEventMap {
		"accordion.itemToggled": {
			nodeId?: string;
			itemIndex: number;
			isOpen: boolean;
		};
	}
}

export interface AccordionNodeProps extends KivNodeComponentProps {
	allowMultiple?: boolean;
	keepOneOpen?: boolean;
	defaultOpenIndex?: number;
	animation?: string;
	animationDuration?: number;
	icon?: string;
	iconPosition?: string;
	iconSize?: number;
	gap?: string;
	borderRadius?: string;
	showSeparator?: boolean;
	separatorColor?: string;
}

export function AccordionNode({
	allowMultiple,
	keepOneOpen,
	defaultOpenIndex,
	animation,
	animationDuration,
	icon,
	iconPosition,
	iconSize,
	gap,
	borderRadius,
	showSeparator,
	separatorColor,
	slots,
	id,
	style,
	...rest
}: AccordionNodeProps) {
	const bus = useContext(KivBusContext);
	const [openIds, setOpenIds] = useState<Set<string>>(() => new Set());
	// Registration order, mirroring Vue's `order` ref — mutated synchronously
	// from AccordionItemNode's mount effect (which always fires before this
	// component's own effects, since React runs child effects before parent
	// effects within a commit), so it's already complete by the time the
	// defaultOpenIndex effect below runs.
	const order = useRef<string[]>([]);

	function isOpen(itemId: string): boolean {
		return openIds.has(itemId);
	}

	function register(itemId: string, defaultOpen: boolean): void {
		order.current = [...order.current, itemId];
		if (defaultOpen) {
			setOpenIds((prev) => {
				const next = allowMultiple ? new Set(prev) : new Set<string>();
				next.add(itemId);
				return next;
			});
		}
	}

	function unregister(itemId: string): void {
		order.current = order.current.filter((existing) => existing !== itemId);
		setOpenIds((prev) => {
			if (!prev.has(itemId)) return prev;
			const next = new Set(prev);
			next.delete(itemId);
			return next;
		});
	}

	function toggle(itemId: string, disabled?: boolean): void {
		if (disabled) return;
		const wasOpen = openIds.has(itemId);
		if (wasOpen) {
			if (keepOneOpen && openIds.size === 1) return;
			const next = new Set(openIds);
			next.delete(itemId);
			setOpenIds(next);
			bus?.emit("accordion.itemToggled", {
				nodeId: id,
				itemIndex: order.current.indexOf(itemId),
				isOpen: false,
			});
		} else {
			const next = allowMultiple ? new Set(openIds) : new Set<string>();
			next.add(itemId);
			setOpenIds(next);
			bus?.emit("accordion.itemToggled", {
				nodeId: id,
				itemIndex: order.current.indexOf(itemId),
				isOpen: true,
			});
		}
	}

	// biome-ignore lint/correctness/useExhaustiveDependencies: runs once on mount, mirroring Vue's onMounted
	useEffect(() => {
		setOpenIds((prev) => {
			if (prev.size > 0) return prev;
			const idx = defaultOpenIndex ?? -1;
			const itemId = idx >= 0 ? order.current[idx] : undefined;
			return itemId ? new Set([itemId]) : prev;
		});
	}, []);

	// biome-ignore lint/correctness/useExhaustiveDependencies: register/unregister close over order (a ref, always current) and the setters/state already listed — their own identity changing every render doesn't change their behavior, so omitting them avoids recomputing this object on every unrelated re-render
	const context: AccordionContextValue = useMemo(
		() => ({
			isOpen,
			toggle,
			register,
			unregister,
			animation: animation ?? "slide",
			animationDuration: animationDuration ?? 200,
			icon: icon ?? "chevron",
			iconPosition: iconPosition ?? "right",
			iconSize: iconSize ?? 12,
		}),
		[
			openIds,
			allowMultiple,
			keepOneOpen,
			id,
			animation,
			animationDuration,
			icon,
			iconPosition,
			iconSize,
			bus,
		],
	);

	const accordionStyle = useMemo(
		() => ({
			display: "flex" as const,
			flexDirection: "column" as const,
			gap: GAP[gap ?? "sm"] ?? "8px",
			borderRadius: RADIUS[borderRadius ?? "md"] ?? "8px",
			["--kiv-accordion-sep" as string]: showSeparator
				? `1px solid ${separatorColor ?? "#e2e8f0"}`
				: undefined,
			...style,
		}),
		[gap, borderRadius, showSeparator, separatorColor, style],
	);

	return (
		<AccordionContext.Provider value={context}>
			<div id={id} style={accordionStyle} data-kiv-type="accordion" {...rest}>
				{slots?.default}
			</div>
		</AccordionContext.Provider>
	);
}

// packages/vue/src/nodes/AccordionNode.vue
<script setup lang="ts">
import { GAP, RADIUS } from "@kivcode/nodes";
import { computed, inject, onMounted, provide, ref } from "vue";
import { KIV_BUS_KEY } from "../bus";
import {
	ACCORDION_CONTEXT_KEY,
	type AccordionContext,
} from "./accordion-context";

declare module "@kivcode/engine" {
	interface KivEventMap {
		"accordion.itemToggled": {
			nodeId?: string;
			itemIndex: number;
			isOpen: boolean;
		};
	}
}

const props = defineProps<{
	nodeId?: string;
	allowMultiple?: boolean;
	keepOneOpen?: boolean;
	defaultOpenIndex?: number;
	animation?: string;
	animationDuration?: number;
	icon?: string;
	iconPosition?: string;
	iconSize?: number;
	gap?: string;
	borderRadius?: string;
	showSeparator?: boolean;
	separatorColor?: string;
}>();

const bus = inject(KIV_BUS_KEY, null);

const openIds = ref<Set<string>>(new Set());
const order = ref<string[]>([]);

function isOpen(id: string): boolean {
	return openIds.value.has(id);
}

function register(id: string, defaultOpen: boolean): void {
	order.value = [...order.value, id];
	if (defaultOpen) {
		const next = props.allowMultiple
			? new Set(openIds.value)
			: new Set<string>();
		next.add(id);
		openIds.value = next;
	}
}

function unregister(id: string): void {
	order.value = order.value.filter((existing) => existing !== id);
	if (openIds.value.has(id)) {
		const next = new Set(openIds.value);
		next.delete(id);
		openIds.value = next;
	}
}

function toggle(id: string, disabled?: boolean): void {
	if (disabled) return;
	const wasOpen = openIds.value.has(id);
	if (wasOpen) {
		if (props.keepOneOpen && openIds.value.size === 1) return;
		const next = new Set(openIds.value);
		next.delete(id);
		openIds.value = next;
	} else {
		const next = props.allowMultiple
			? new Set(openIds.value)
			: new Set<string>();
		next.add(id);
		openIds.value = next;
	}
	bus?.emit("accordion.itemToggled", {
		nodeId: props.nodeId,
		itemIndex: order.value.indexOf(id),
		isOpen: openIds.value.has(id),
	});
}

onMounted(() => {
	if (openIds.value.size > 0) return;
	const idx = props.defaultOpenIndex ?? -1;
	const id = idx >= 0 ? order.value[idx] : undefined;
	if (id) openIds.value = new Set([id]);
});

const context: AccordionContext = {
	isOpen,
	toggle,
	register,
	unregister,
	animation: computed(() => props.animation ?? "slide"),
	animationDuration: computed(() => props.animationDuration ?? 200),
	icon: computed(() => props.icon ?? "chevron"),
	iconPosition: computed(() => props.iconPosition ?? "right"),
	iconSize: computed(() => props.iconSize ?? 12),
};
provide(ACCORDION_CONTEXT_KEY, context);

const accordionStyle = computed(() => ({
	display: "flex" as const,
	flexDirection: "column" as const,
	gap: GAP[props.gap ?? "sm"] ?? "8px",
	borderRadius: RADIUS[props.borderRadius ?? "md"] ?? "8px",
	"--kiv-accordion-sep": props.showSeparator
		? `1px solid ${props.separatorColor ?? "#e2e8f0"}`
		: undefined,
}));
</script>

<template>
	<div :style="accordionStyle" data-kiv-type="accordion">
		<slot />
	</div>
</template>
