// packages/react/src/nodes/SpacerNode.tsx
import { fromScale, SPACING } from "@kivcode/nodes";
import { useContext, useMemo } from "react";
import { KivEditorModeContext } from "../editor-mode";
import type { KivNodeComponentProps } from "../node-props";

export interface SpacerNodeProps extends KivNodeComponentProps {
	height?: string;
	showDividerOnCanvas?: boolean;
}

export function SpacerNode({
	height,
	showDividerOnCanvas = true,
	id,
	style,
	...rest
}: SpacerNodeProps) {
	const isEditorMode = useContext(KivEditorModeContext);

	const spacerStyle = useMemo(
		() => ({
			height: fromScale(SPACING, height ?? "16px", "16px"),
			width: "100%",
			...(isEditorMode && showDividerOnCanvas
				? {
						outline: "1px dashed rgba(99, 102, 241, 0.4)",
						outlineOffset: "-1px",
					}
				: null),
			...style,
		}),
		[height, isEditorMode, showDividerOnCanvas, style],
	);

	return <div id={id} style={spacerStyle} data-kiv-type="spacer" {...rest} />;
}

// packages/vue/src/nodes/SpacerNode.vue
<script setup lang="ts">
import { fromScale, SPACING } from "@kivcode/nodes";
import { computed, inject } from "vue";
import { KIV_EDITOR_MODE_KEY } from "../editor-mode";

const props = withDefaults(
	defineProps<{
		height?: string;
		showDividerOnCanvas?: boolean;
	}>(),
	{ showDividerOnCanvas: true },
);

const isEditorMode = inject(KIV_EDITOR_MODE_KEY, false);

const spacerStyle = computed(() => ({
	height: fromScale(SPACING, props.height ?? "16px", "16px"),
	width: "100%",
}));

const showGuide = computed(() => isEditorMode && props.showDividerOnCanvas);
</script>

<template>
	<div :style="spacerStyle" :class="{ 'kiv-spacer--guide': showGuide }" data-kiv-type="spacer" />
</template>

<style scoped>
.kiv-spacer--guide {
	outline: 1px dashed rgba(99, 102, 241, 0.4);
	outline-offset: -1px;
}
</style>
