// packages/react/src/nodes/StackNode.tsx
import {
	GAP,
	RADIUS,
	resolveSpacingStyle,
	SHADOW,
	SPACING,
} from "@kivcode/nodes";
import { useMemo } from "react";
import type { KivNodeComponentProps } from "../node-props";

export interface StackNodeProps extends KivNodeComponentProps {
	direction?: string;
	gap?: string;
	align?: string;
	justify?: string;
	wrap?: boolean;
	paddingY?: string;
	paddingX?: string;
	marginY?: string;
	marginX?: string;
	paddingBox?: unknown;
	marginBox?: unknown;
	background?: string;
	borderRadius?: string;
	shadow?: string;
	borderTopWidth?: number;
	borderRightWidth?: number;
	borderBottomWidth?: number;
	borderLeftWidth?: number;
	borderStyle?: string;
	borderColor?: string;
}

export function StackNode({
	direction,
	gap,
	align,
	justify,
	wrap,
	paddingY,
	paddingX,
	marginY,
	marginX,
	paddingBox,
	marginBox,
	background,
	borderRadius,
	shadow,
	borderTopWidth,
	borderRightWidth,
	borderBottomWidth,
	borderLeftWidth,
	borderStyle,
	borderColor,
	slots,
	id,
	style,
	...rest
}: StackNodeProps) {
	const stackStyle = useMemo(() => {
		const borderWidths = {
			top: borderTopWidth ?? 0,
			right: borderRightWidth ?? 0,
			bottom: borderBottomWidth ?? 0,
			left: borderLeftWidth ?? 0,
		};
		const hasBorder = Object.values(borderWidths).some((w) => w > 0);
		const bStyle = borderStyle ?? "solid";
		const bColor = borderColor ?? "#e2e8f0";
		const py = SPACING[paddingY ?? "none"] ?? "0";
		const px = SPACING[paddingX ?? "none"] ?? "0";
		const my = SPACING[marginY ?? "none"] ?? "0";
		const mx = SPACING[marginX ?? "none"] ?? "0";

		return {
			display: "flex" as const,
			flexDirection: (direction === "row" ? "row" : "column") as
				| "row"
				| "column",
			gap: GAP[gap ?? "md"] ?? "16px",
			alignItems: align ?? "flex-start",
			justifyContent: justify ?? "flex-start",
			flexWrap: (wrap ? "wrap" : "nowrap") as "wrap" | "nowrap",
			// Per-side override, shared with every other node that needs this
			// escape hatch (see packages/nodes/src/spacing-field.ts). Empty side
			// falls back to the Y/X shorthand above.
			...resolveSpacingStyle("padding", paddingBox, {
				top: py,
				right: px,
				bottom: py,
				left: px,
			}),
			...resolveSpacingStyle("margin", marginBox, {
				top: my,
				right: mx,
				bottom: my,
				left: mx,
			}),
			background:
				background && background !== "transparent" ? background : undefined,
			borderRadius: RADIUS[borderRadius ?? "none"] ?? "0",
			boxShadow: SHADOW[shadow ?? "none"] ?? "none",
			borderTop: borderWidths.top
				? `${borderWidths.top}px ${bStyle} ${bColor}`
				: undefined,
			borderRight: borderWidths.right
				? `${borderWidths.right}px ${bStyle} ${bColor}`
				: undefined,
			borderBottom: borderWidths.bottom
				? `${borderWidths.bottom}px ${bStyle} ${bColor}`
				: undefined,
			borderLeft: borderWidths.left
				? `${borderWidths.left}px ${bStyle} ${bColor}`
				: undefined,
			boxSizing: hasBorder ? ("border-box" as const) : undefined,
			...style,
		};
	}, [
		direction,
		gap,
		align,
		justify,
		wrap,
		paddingY,
		paddingX,
		marginY,
		marginX,
		paddingBox,
		marginBox,
		background,
		borderRadius,
		shadow,
		borderTopWidth,
		borderRightWidth,
		borderBottomWidth,
		borderLeftWidth,
		borderStyle,
		borderColor,
		style,
	]);

	return (
		<div id={id} style={stackStyle} data-kiv-type="stack" {...rest}>
			{slots?.default}
		</div>
	);
}

// packages/vue/src/nodes/StackNode.vue
<script setup lang="ts">
import {
	GAP,
	RADIUS,
	resolveSpacingStyle,
	SHADOW,
	SPACING,
} from "@kivcode/nodes";
import { computed } from "vue";

const props = defineProps<{
	direction?: string;
	gap?: string;
	align?: string;
	justify?: string;
	wrap?: boolean;
	paddingY?: string;
	paddingX?: string;
	marginY?: string;
	marginX?: string;
	paddingBox?: unknown;
	marginBox?: unknown;
	background?: string;
	borderRadius?: string;
	shadow?: string;
	borderTopWidth?: number;
	borderRightWidth?: number;
	borderBottomWidth?: number;
	borderLeftWidth?: number;
	borderStyle?: string;
	borderColor?: string;
}>();

const stackStyle = computed(() => {
	const borderWidths = {
		top: props.borderTopWidth ?? 0,
		right: props.borderRightWidth ?? 0,
		bottom: props.borderBottomWidth ?? 0,
		left: props.borderLeftWidth ?? 0,
	};
	const hasBorder = Object.values(borderWidths).some((w) => w > 0);
	const borderStyle = props.borderStyle ?? "solid";
	const borderColor = props.borderColor ?? "#e2e8f0";
	const paddingY = SPACING[props.paddingY ?? "none"] ?? "0";
	const paddingX = SPACING[props.paddingX ?? "none"] ?? "0";
	const marginY = SPACING[props.marginY ?? "none"] ?? "0";
	const marginX = SPACING[props.marginX ?? "none"] ?? "0";

	return {
		display: "flex" as const,
		flexDirection: (props.direction === "row" ? "row" : "column") as
			| "row"
			| "column",
		gap: GAP[props.gap ?? "md"] ?? "16px",
		alignItems: props.align ?? "flex-start",
		justifyContent: props.justify ?? "flex-start",
		flexWrap: (props.wrap ? "wrap" : "nowrap") as "wrap" | "nowrap",
		// Per-side override, shared with every other node that needs this
		// escape hatch (see packages/nodes/src/spacing-field.ts). Empty side
		// falls back to the Y/X shorthand above.
		...resolveSpacingStyle("padding", props.paddingBox, {
			top: paddingY,
			right: paddingX,
			bottom: paddingY,
			left: paddingX,
		}),
		...resolveSpacingStyle("margin", props.marginBox, {
			top: marginY,
			right: marginX,
			bottom: marginY,
			left: marginX,
		}),
		background:
			props.background && props.background !== "transparent"
				? props.background
				: undefined,
		borderRadius: RADIUS[props.borderRadius ?? "none"] ?? "0",
		boxShadow: SHADOW[props.shadow ?? "none"] ?? "none",
		borderTop: borderWidths.top
			? `${borderWidths.top}px ${borderStyle} ${borderColor}`
			: undefined,
		borderRight: borderWidths.right
			? `${borderWidths.right}px ${borderStyle} ${borderColor}`
			: undefined,
		borderBottom: borderWidths.bottom
			? `${borderWidths.bottom}px ${borderStyle} ${borderColor}`
			: undefined,
		borderLeft: borderWidths.left
			? `${borderWidths.left}px ${borderStyle} ${borderColor}`
			: undefined,
		boxSizing: hasBorder ? ("border-box" as const) : undefined,
	};
});
</script>

<template>
	<div :style="stackStyle" data-kiv-type="stack">
		<slot />
	</div>
</template>
