// packages/react/src/nodes/TextNode.tsx
import { LETTER_SPACING, LINE_HEIGHT } from "@kivcode/nodes";
import { useMemo } from "react";
import type { KivNodeComponentProps } from "../node-props";

export interface TextNodeProps extends KivNodeComponentProps {
	content?: string;
	size?: number;
	weight?: string;
	color?: string;
	align?: string;
	lineHeight?: string;
	letterSpacing?: string;
}

export function TextNode({
	content,
	size,
	weight,
	color,
	align,
	lineHeight,
	letterSpacing,
	id,
	style,
	...rest
}: TextNodeProps) {
	const textStyle = useMemo(
		() => ({
			fontSize: `${size ?? 16}px`,
			fontWeight: weight ?? "400",
			color: color ?? "inherit",
			textAlign: (align ?? "left") as "left" | "center" | "right" | "justify",
			lineHeight: LINE_HEIGHT[lineHeight ?? "relaxed"] ?? "1.6",
			letterSpacing: LETTER_SPACING[letterSpacing ?? "normal"] ?? "0em",
			margin: "0",
			...style,
		}),
		[size, weight, color, align, lineHeight, letterSpacing, style],
	);

	return (
		<p id={id} style={textStyle} data-kiv-type="text" {...rest}>
			{content}
		</p>
	);
}

// packages/vue/src/nodes/TextNode.vue
<script setup lang="ts">
import { LETTER_SPACING, LINE_HEIGHT } from "@kivcode/nodes";
import { computed } from "vue";

const props = defineProps<{
	content?: string;
	size?: number;
	weight?: string;
	color?: string;
	align?: string;
	lineHeight?: string;
	letterSpacing?: string;
}>();

const textStyle = computed(() => ({
	fontSize: `${props.size ?? 16}px`,
	fontWeight: props.weight ?? "400",
	color: props.color ?? "inherit",
	textAlign: (props.align ?? "left") as "left" | "center" | "right" | "justify",
	lineHeight: LINE_HEIGHT[props.lineHeight ?? "relaxed"] ?? "1.6",
	letterSpacing: LETTER_SPACING[props.letterSpacing ?? "normal"] ?? "0em",
	margin: "0",
}));
</script>

<template>
	<p :style="textStyle" data-kiv-type="text">{{ content }}</p>
</template>
