// packages/vue/src/KivNodeRenderer.vue
<script setup lang="ts">
import type { KivNode } from "@kivcode/engine";
import { resolveNode, resolveResponsive } from "@kivcode/engine";
import type { ComputedRef } from "vue";
import { computed, inject } from "vue";
import type { KivRenderContext } from "./context";
import { KIV_CONTEXT_KEY } from "./context";
import { KIV_EDITOR_MODE_KEY } from "./editor-mode";

const props = defineProps<{ node: KivNode }>();

const ctx = inject<ComputedRef<KivRenderContext> | KivRenderContext>(
	KIV_CONTEXT_KEY,
);
const isEditorMode = inject(KIV_EDITOR_MODE_KEY, false);

const resolvedCtx = computed(() =>
	ctx ? ("value" in ctx ? ctx.value : ctx) : null,
);

// Hidden-for-this-breakpoint nodes render nothing in production, but stay
// visible-and-dimmed in the editor so they can still be selected and un-hidden.
const isVisible = computed(() => {
	const breakpoint = resolvedCtx.value?.resolveCtx.breakpoint ?? "base";
	return resolveResponsive<boolean>(props.node.visible, breakpoint) !== false;
});
const shouldRender = computed(() => isVisible.value || isEditorMode);
const editorHiddenStyle = computed(() =>
	isEditorMode && !isVisible.value ? { opacity: "0.35" } : undefined,
);

const resolved = computed(() => {
	const c = resolvedCtx.value;
	if (!c)
		return {
			id: props.node.id,
			type: props.node.type,
			props: props.node.props,
		};
	return resolveNode(props.node, c.resolveCtx);
});

const component = computed(() => {
	const c = resolvedCtx.value;
	if (!c) return null;
	return c.registry.get(props.node.type) ?? null;
});

const slotEntries = computed(() => Object.entries(props.node.slots ?? {}));

function onDragStart(e: DragEvent) {
	if (!isEditorMode || !e.dataTransfer) return;
	e.dataTransfer.setData("text/plain", resolved.value.id);
	e.dataTransfer.effectAllowed = "move";
}
</script>

<template>
	<component
		v-if="component && shouldRender"
		:is="component"
		v-bind="resolved.props"
		:id="resolved.id"
		:node-id="resolved.id"
		:data-kiv-node-id="resolved.id"
		:data-kiv-hidden="isVisible ? undefined : 'true'"
		:draggable="isEditorMode || undefined"
		:style="editorHiddenStyle"
		@dragstart="onDragStart"
	>
		<template v-for="[slotName, children] in slotEntries" #[slotName]="slotProps">
			<KivNodeRenderer
				v-for="child in children"
				:key="child.id"
				:node="child"
				v-bind="slotProps"
			/>
		</template>
	</component>
	<div v-else-if="shouldRender" style="display:none" :data-kiv-unknown="node.type" />
</template>

// packages/react/src/KivNodeRenderer.tsx
import type { KivNode } from "@kivcode/engine";
import { resolveNode, resolveResponsive } from "@kivcode/engine";
import {
	createElement,
	type DragEvent,
	type ReactNode,
	useContext,
	useMemo,
} from "react";
import { KivContext } from "./context";
import { KivEditorModeContext } from "./editor-mode";

export interface KivNodeRendererProps {
	node: KivNode;
}

export function KivNodeRenderer({ node }: KivNodeRendererProps) {
	const ctx = useContext(KivContext);
	const isEditorMode = useContext(KivEditorModeContext);

	const breakpoint = ctx?.resolveCtx.breakpoint ?? "base";
	// Hidden-for-this-breakpoint nodes render nothing in production, but stay
	// visible-and-dimmed in the editor so they can still be selected and un-hidden.
	const isVisible =
		resolveResponsive<boolean>(node.visible, breakpoint) !== false;
	const shouldRender = isVisible || isEditorMode;

	const resolved = useMemo(
		() =>
			ctx
				? resolveNode(node, ctx.resolveCtx)
				: { id: node.id, type: node.type, props: node.props },
		[node, ctx],
	);

	const Component = ctx?.registry.get(node.type) ?? null;

	// Vue's named `<slot>` outlets, but eager: every child is already a
	// rendered <KivNodeRenderer>, bucketed by slot name. The node component
	// just places `slots.default` (or a named slot) where it wants children.
	// biome-ignore lint/correctness/useExhaustiveDependencies: KivNodeRenderer is this module's own top-level function declaration, not a prop/state value — its identity never changes
	const slots = useMemo(() => {
		const entries = Object.entries(node.slots ?? {});
		const out: Record<string, ReactNode[]> = {};
		for (const [name, children] of entries) {
			out[name] = children.map((child) => (
				<KivNodeRenderer key={child.id} node={child} />
			));
		}
		return out;
	}, [node.slots]);

	if (!shouldRender) return null;

	if (!Component) {
		return <div style={{ display: "none" }} data-kiv-unknown={node.type} />;
	}

	function onDragStart(e: DragEvent) {
		if (!isEditorMode) return;
		e.dataTransfer.setData("text/plain", resolved.id);
		e.dataTransfer.effectAllowed = "move";
	}

	return createElement(Component, {
		...resolved.props,
		id: resolved.id,
		"data-kiv-node-id": resolved.id,
		"data-kiv-hidden": isVisible ? undefined : "true",
		draggable: isEditorMode || undefined,
		style: isEditorMode && !isVisible ? { opacity: 0.35 } : undefined,
		onDragStart,
		slots,
	});
}
