// packages/react-editor/src/inspector/controls/MediaPicker.tsx
import type { FieldDescriptor } from "@kivcode/engine";
import { useContext } from "react";
import { FileTypeIcon } from "../../components/FileTypeIcon";
import { EditorStoreContext } from "../../store/context";

export interface MediaPickerProps {
	value?: string;
	/** Part of the common plugin-control contract; unused here (same as the Vue original, which never declared it either). */
	fieldKey?: string;
	descriptor?: FieldDescriptor;
	onChange: (value: string) => void;
}

// This same control is used for image, video, AND non-visual media fields
// (e.g. a PDF/DOC attachment link) — an <img> preview of a non-image URL
// just shows a broken-image icon with no indication of what the file even
// is, so branch on the extension instead of assuming everything is an image.
const VIDEO_RE = /\.(mp4|webm|mov|m4v|ogv|avi)(\?.*)?$/i;
const OTHER_FILE_RE =
	/\.(pdf|docx?|xlsx?|csv|pptx?|zip|rar|7z|tar|gz|txt|md|mp3|wav|ogg|m4a|flac)(\?.*)?$/i;

export function MediaPicker({
	value = "",
	fieldKey: _fieldKey,
	descriptor,
	onChange,
}: MediaPickerProps) {
	const store = useContext(EditorStoreContext);
	const media = store?.media ?? null;

	const isVideo = VIDEO_RE.test(value);
	const isOtherFile = OTHER_FILE_RE.test(value);

	function clear() {
		onChange("");
	}

	function browseMedia() {
		// TODO: open KivMediaBrowser once ported
	}

	return (
		<div className="kiv-media-picker">
			{value && (
				<div className="kiv-media-picker__preview">
					{isVideo ? (
						<video src={value} muted className="kiv-media-picker__thumb">
							<track kind="captions" />
						</video>
					) : isOtherFile ? (
						<div className="kiv-media-picker__thumb kiv-media-picker__thumb--file">
							<FileTypeIcon url={value} />
						</div>
					) : (
						<img src={value} alt="" className="kiv-media-picker__thumb" />
					)}
					<button
						type="button"
						className="kiv-media-picker__clear"
						title="Clear"
						onClick={clear}
					>
						&times;
					</button>
				</div>
			)}
			<input
				type="text"
				className="kiv-media-picker__input"
				value={value}
				placeholder={descriptor?.placeholder ?? "https://…"}
				onChange={(e) => onChange(e.target.value)}
			/>
			<button
				type="button"
				className="kiv-media-picker__browse"
				disabled={!media}
				onClick={browseMedia}
			>
				Browse Media
			</button>
			{!media && (
				<p className="kiv-media-picker__hint">
					No media provider configured — paste a URL directly.
				</p>
			)}
		</div>
	);
}

// packages/vue-editor/src/inspector/controls/MediaPicker.vue
<script setup lang="ts">
import type { FieldDescriptor, MediaAsset } from "@kivcode/engine";
import { computed, inject, ref } from "vue";
import FileTypeIcon from "../../components/FileTypeIcon.vue";
import KivMediaBrowser from "../../components/KivMediaBrowser.vue";
import { EDITOR_STORE_KEY } from "../../store/context";

const props = withDefaults(
	defineProps<{
		modelValue?: string;
		descriptor?: FieldDescriptor;
	}>(),
	{ modelValue: "" },
);

const emit = defineEmits<{
	"update:modelValue": [value: string];
}>();

const store = inject(EDITOR_STORE_KEY, null);
const media = computed(() => store?.media ?? null);
const browserOpen = ref(false);

// This same control is used for image, video, AND non-visual media fields
// (e.g. a PDF/DOC attachment link) — an <img> preview of a non-image URL
// just shows a broken-image icon with no indication of what the file even
// is, so branch on the extension instead of assuming everything is an image.
const isVideo = computed(() =>
	/\.(mp4|webm|mov|m4v|ogv|avi)(\?.*)?$/i.test(props.modelValue),
);
const isOtherFile = computed(() =>
	/\.(pdf|docx?|xlsx?|csv|pptx?|zip|rar|7z|tar|gz|txt|md|mp3|wav|ogg|m4a|flac)(\?.*)?$/i.test(
		props.modelValue,
	),
);

function selectAsset(asset: MediaAsset) {
	emit("update:modelValue", asset.url);
	browserOpen.value = false;
}

function clear() {
	emit("update:modelValue", "");
}
</script>

<template>
	<div class="kiv-media-picker">
		<div v-if="modelValue" class="kiv-media-picker__preview">
			<video v-if="isVideo" :src="modelValue" muted class="kiv-media-picker__thumb" />
			<div v-else-if="isOtherFile" class="kiv-media-picker__thumb kiv-media-picker__thumb--file">
				<FileTypeIcon :url="modelValue" />
			</div>
			<img v-else :src="modelValue" alt="" class="kiv-media-picker__thumb" />
			<button
				type="button"
				class="kiv-media-picker__clear"
				title="Clear"
				@click="clear"
			>
				&times;
			</button>
		</div>
		<input
			type="text"
			class="kiv-media-picker__input"
			:value="modelValue"
			:placeholder="descriptor?.placeholder ?? 'https://…'"
			@input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
		/>
		<button
			type="button"
			class="kiv-media-picker__browse"
			:disabled="!media"
			@click="browserOpen = true"
		>
			Browse Media
		</button>
		<p v-if="!media" class="kiv-media-picker__hint">
			No media provider configured — paste a URL directly.
		</p>
		<KivMediaBrowser
			:open="browserOpen"
			:media="media"
			@close="browserOpen = false"
			@select="selectAsset"
		/>
	</div>
</template>

<style scoped>
.kiv-media-picker {
	display: flex;
	flex-direction: column;
	gap: 6px;
}

.kiv-media-picker__preview {
	position: relative;
	width: 100%;
	height: 72px;
	border-radius: 6px;
	overflow: hidden;
	background: var(--color-surface-sunken);
}
.kiv-media-picker__thumb {
	width: 100%;
	height: 100%;
	object-fit: cover;
	display: block;
}
.kiv-media-picker__thumb--file {
	display: flex;
	align-items: center;
	justify-content: center;
}
.kiv-media-picker__clear {
	position: absolute;
	top: 4px;
	right: 4px;
	width: 20px;
	height: 20px;
	display: flex;
	align-items: center;
	justify-content: center;
	background: rgba(0, 0, 0, 0.55);
	border: none;
	border-radius: 50%;
	color: #fff;
	cursor: pointer;
	line-height: 1;
	font-size: 0.9rem;
}
.kiv-media-picker__clear:hover {
	background: rgba(0, 0, 0, 0.75);
}

.kiv-media-picker__input {
	width: 100%;
	padding: 5px 8px;
	background: var(--color-surface-base);
	border: 1px solid var(--color-border);
	border-radius: 5px;
	color: var(--color-text-primary);
	font-size: 0.72rem;
	font-family: inherit;
	outline: none;
	box-sizing: border-box;
}
.kiv-media-picker__input:focus {
	border-color: var(--color-accent);
}

.kiv-media-picker__browse {
	width: 100%;
	padding: 6px 8px;
	background: var(--color-surface-overlay);
	border: 1px solid var(--color-border);
	border-radius: 5px;
	color: var(--color-text-primary);
	font-size: 0.72rem;
	font-weight: 600;
	font-family: inherit;
	cursor: pointer;
}
.kiv-media-picker__browse:hover:not(:disabled) {
	border-color: var(--color-accent);
}
.kiv-media-picker__browse:disabled {
	opacity: 0.5;
	cursor: not-allowed;
}

.kiv-media-picker__hint {
	margin: 0;
	font-size: 0.65rem;
	color: var(--color-text-muted);
}
</style>
