// packages/vue/src/nodes/CountdownNode.vue
<script setup lang="ts">
import {
	computeCountdownParts,
	resolveCountdownTypographyStyle,
} from "@kivcode/nodes";
import { computed, onBeforeUnmount, onMounted, ref } from "vue";

const props = withDefaults(
	defineProps<{
		targetDate?: string;
		expiredMessage?: string;
		daysLabel?: string;
		hoursLabel?: string;
		minutesLabel?: string;
		secondsLabel?: string;
		showLabels?: boolean;
		countdownStyle?: string;
		fontFamily?: string;
		size?: number;
		weight?: string;
		color?: string;
	}>(),
	{ showLabels: true },
);

const now = ref(Date.now());
let timer: ReturnType<typeof setInterval> | null = null;
onMounted(() => {
	timer = setInterval(() => {
		now.value = Date.now();
	}, 1000);
});
onBeforeUnmount(() => {
	if (timer) clearInterval(timer);
});

const parts = computed(() =>
	computeCountdownParts(props.targetDate, now.value),
);

const displayStyle = computed(() => props.countdownStyle ?? "boxes");
const numberStyle = computed(() =>
	resolveCountdownTypographyStyle({
		fontFamily: props.fontFamily,
		size: props.size,
		weight: props.weight,
		color: props.color,
		minimal: displayStyle.value === "minimal",
	}),
);

const units = computed(() => [
	{ value: parts.value.days, label: props.daysLabel ?? "Days" },
	{ value: parts.value.hours, label: props.hoursLabel ?? "Hours" },
	{ value: parts.value.minutes, label: props.minutesLabel ?? "Min" },
	{ value: parts.value.seconds, label: props.secondsLabel ?? "Sec" },
]);

function pad(value: number): string {
	return String(value).padStart(2, "0");
}
</script>

<template>
	<div data-kiv-type="countdown">
		<time v-if="parts.expired" :datetime="targetDate ?? ''">
			{{ expiredMessage ?? "Time's up!" }}
		</time>
		<time v-else :datetime="targetDate ?? ''" style="display: contents">
			<div
				class="kiv-countdown"
				:style="{ display: 'flex', alignItems: 'center', gap: displayStyle === 'inline' ? '6px' : '12px' }"
			>
				<template v-for="(unit, i) in units" :key="unit.label">
					<div
						class="kiv-countdown__unit"
						:class="{ 'kiv-countdown__unit--boxes': displayStyle === 'boxes' }"
					>
						<span
							class="kiv-countdown__value"
							:style="numberStyle"
						>{{ pad(unit.value) }}</span>
						<span v-if="showLabels" class="kiv-countdown__label">{{ unit.label }}</span>
					</div>
					<span v-if="displayStyle === 'inline' && i < units.length - 1" class="kiv-countdown__sep">:</span>
				</template>
			</div>
		</time>
	</div>
</template>

<style scoped>
.kiv-countdown__unit {
	display: flex;
	flex-direction: column;
	align-items: center;
}
.kiv-countdown__unit--boxes {
	padding: 12px 16px;
	border-radius: 8px;
	background: rgba(99, 102, 241, 0.08);
	min-width: 64px;
}
.kiv-countdown__value {
	font-weight: 700;
	line-height: 1;
}
.kiv-countdown__label {
	font-size: 11px;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: #64748b;
}
.kiv-countdown__sep {
	opacity: 0.5;
}
</style>

// packages/react/src/nodes/CountdownNode.tsx
import {
	computeCountdownParts,
	resolveCountdownTypographyStyle,
} from "@kivcode/nodes";
import { Fragment, useEffect, useMemo, useState } from "react";
import type { KivNodeComponentProps } from "../node-props";

function pad(value: number): string {
	return String(value).padStart(2, "0");
}

export interface CountdownNodeProps extends KivNodeComponentProps {
	targetDate?: string;
	expiredMessage?: string;
	daysLabel?: string;
	hoursLabel?: string;
	minutesLabel?: string;
	secondsLabel?: string;
	showLabels?: boolean;
	countdownStyle?: string;
	fontFamily?: string;
	size?: number;
	weight?: string;
	color?: string;
}

export function CountdownNode({
	targetDate,
	expiredMessage,
	daysLabel,
	hoursLabel,
	minutesLabel,
	secondsLabel,
	showLabels = true,
	countdownStyle,
	fontFamily,
	size,
	weight,
	color,
	id,
	style,
	...rest
}: CountdownNodeProps) {
	const [now, setNow] = useState(() => Date.now());

	useEffect(() => {
		const timer = setInterval(() => {
			setNow(Date.now());
		}, 1000);
		return () => clearInterval(timer);
	}, []);

	const parts = useMemo(
		() => computeCountdownParts(targetDate, now),
		[targetDate, now],
	);

	const displayStyle = countdownStyle ?? "boxes";
	const numberStyle = resolveCountdownTypographyStyle({
		fontFamily,
		size,
		weight,
		color,
		minimal: displayStyle === "minimal",
	});

	const units = [
		{ value: parts.days, label: daysLabel ?? "Days" },
		{ value: parts.hours, label: hoursLabel ?? "Hours" },
		{ value: parts.minutes, label: minutesLabel ?? "Min" },
		{ value: parts.seconds, label: secondsLabel ?? "Sec" },
	];

	if (parts.expired) {
		return (
			<div id={id} style={style} data-kiv-type="countdown" {...rest}>
				<time dateTime={targetDate ?? ""}>
					{expiredMessage ?? "Time's up!"}
				</time>
			</div>
		);
	}

	return (
		<div id={id} style={style} data-kiv-type="countdown" {...rest}>
			<time dateTime={targetDate ?? ""} style={{ display: "contents" }}>
				<div
					className="kiv-countdown"
					style={{
						display: "flex",
						alignItems: "center",
						gap: displayStyle === "inline" ? "6px" : "12px",
					}}
				>
					{units.map((unit, i) => (
						<Fragment key={unit.label}>
							<div
								className={`kiv-countdown__unit${displayStyle === "boxes" ? " kiv-countdown__unit--boxes" : ""}`}
								style={
									displayStyle === "boxes"
										? {
												display: "flex",
												flexDirection: "column",
												alignItems: "center",
												padding: "12px 16px",
												borderRadius: "8px",
												background: "rgba(99, 102, 241, 0.08)",
												minWidth: "64px",
											}
										: {
												display: "flex",
												flexDirection: "column",
												alignItems: "center",
											}
								}
							>
								<span
									className="kiv-countdown__value"
									style={{ ...numberStyle, lineHeight: "1" }}
								>
									{pad(unit.value)}
								</span>
								{showLabels && (
									<span
										className="kiv-countdown__label"
										style={{
											fontSize: "11px",
											textTransform: "uppercase",
											letterSpacing: "0.05em",
											color: "#64748b",
										}}
									>
										{unit.label}
									</span>
								)}
							</div>
							{displayStyle === "inline" && i < units.length - 1 && (
								<span className="kiv-countdown__sep" style={{ opacity: 0.5 }}>
									:
								</span>
							)}
						</Fragment>
					))}
				</div>
			</time>
		</div>
	);
}
