// packages/vue/src/nodes/FormNode.vue
<script setup lang="ts">
import { GAP } from "@kivcode/nodes";
import { computed, inject, ref } from "vue";
import { KIV_SERVICES_KEY } from "../services";

const props = defineProps<{
	submitLabel?: string;
	submitUrl?: string;
	method?: string;
	successMessage?: string;
	errorMessage?: string;
	layout?: string;
	gap?: string;
}>();

const services = inject(KIV_SERVICES_KEY, null);
const status = ref<"idle" | "submitting" | "success" | "error">("idle");

const formStyle = computed(() => {
	const layout = props.layout ?? "stacked";
	return {
		display: layout === "grid-2" ? ("grid" as const) : ("flex" as const),
		gridTemplateColumns: layout === "grid-2" ? "1fr 1fr" : undefined,
		flexDirection: layout === "stacked" ? ("column" as const) : undefined,
		flexWrap: layout === "inline" ? ("wrap" as const) : undefined,
		alignItems: layout === "inline" ? ("flex-end" as const) : undefined,
		gap: GAP[props.gap ?? "md"] ?? "16px",
	};
});

const submitButtonStyle = computed(() => ({
	gridColumn: (props.layout ?? "stacked") === "grid-2" ? "1 / -1" : undefined,
}));

// No ApiClient configured (services.api is undefined) — don't intercept the
// submit, let the browser POST/GET to submitUrl natively (progressive
// enhancement instead of a hard requirement on a backend integration).
async function onSubmit(event: Event) {
	if (!services?.api) return;
	event.preventDefault();
	const form = event.target as HTMLFormElement;
	const data = Object.fromEntries(new FormData(form).entries());
	status.value = "submitting";
	try {
		await services.api.post(props.submitUrl ?? "", data);
		status.value = "success";
		form.reset();
	} catch {
		status.value = "error";
	}
}
</script>

<template>
	<form
		:action="submitUrl"
		:method="method ?? 'post'"
		:style="formStyle"
		data-kiv-type="form"
		@submit="onSubmit"
	>
		<slot />
		<button type="submit" :disabled="status === 'submitting'" :style="submitButtonStyle">
			{{ submitLabel ?? "Submit" }}
		</button>
		<p v-if="status === 'success'" class="kiv-form__message kiv-form__message--success">
			{{ successMessage ?? "Thank you!" }}
		</p>
		<p v-if="status === 'error'" class="kiv-form__message kiv-form__message--error">
			{{ errorMessage ?? "Something went wrong." }}
		</p>
	</form>
</template>

<style scoped>
.kiv-form__message {
	margin: 0;
	font-size: 14px;
}
.kiv-form__message--success {
	color: #16a34a;
}
.kiv-form__message--error {
	color: #dc2626;
}
</style>

// packages/react/src/nodes/FormNode.tsx
import { GAP } from "@kivcode/nodes";
import { type FormEvent, useContext, useMemo, useState } from "react";
import type { KivNodeComponentProps } from "../node-props";
import { KivServicesContext } from "../services";

export interface FormNodeProps extends KivNodeComponentProps {
	submitLabel?: string;
	submitUrl?: string;
	method?: string;
	successMessage?: string;
	errorMessage?: string;
	layout?: string;
	gap?: string;
}

type Status = "idle" | "submitting" | "success" | "error";

export function FormNode({
	submitLabel,
	submitUrl,
	method,
	successMessage,
	errorMessage,
	layout,
	gap,
	slots,
	id,
	style,
	...rest
}: FormNodeProps) {
	const services = useContext(KivServicesContext);
	const [status, setStatus] = useState<Status>("idle");

	const formStyle = useMemo(() => {
		const resolvedLayout = layout ?? "stacked";
		return {
			display:
				resolvedLayout === "grid-2" ? ("grid" as const) : ("flex" as const),
			gridTemplateColumns: resolvedLayout === "grid-2" ? "1fr 1fr" : undefined,
			flexDirection:
				resolvedLayout === "stacked" ? ("column" as const) : undefined,
			flexWrap: resolvedLayout === "inline" ? ("wrap" as const) : undefined,
			alignItems:
				resolvedLayout === "inline" ? ("flex-end" as const) : undefined,
			gap: GAP[gap ?? "md"] ?? "16px",
			...style,
		};
	}, [layout, gap, style]);

	const submitButtonStyle = useMemo(
		() => ({
			gridColumn: (layout ?? "stacked") === "grid-2" ? "1 / -1" : undefined,
		}),
		[layout],
	);

	// No ApiClient configured (services.api is undefined) — don't intercept the
	// submit, let the browser POST/GET to submitUrl natively (progressive
	// enhancement instead of a hard requirement on a backend integration).
	async function onSubmit(event: FormEvent<HTMLFormElement>) {
		if (!services?.api) return;
		event.preventDefault();
		const form = event.currentTarget;
		const data = Object.fromEntries(new FormData(form).entries());
		setStatus("submitting");
		try {
			await services.api.post(submitUrl ?? "", data);
			setStatus("success");
			form.reset();
		} catch {
			setStatus("error");
		}
	}

	return (
		<form
			id={id}
			action={submitUrl}
			method={method ?? "post"}
			style={formStyle}
			data-kiv-type="form"
			onSubmit={onSubmit}
			{...rest}
		>
			{slots?.default}
			<button
				type="submit"
				disabled={status === "submitting"}
				style={submitButtonStyle}
			>
				{submitLabel ?? "Submit"}
			</button>
			{status === "success" && (
				<p className="kiv-form__message kiv-form__message--success">
					{successMessage ?? "Thank you!"}
				</p>
			)}
			{status === "error" && (
				<p className="kiv-form__message kiv-form__message--error">
					{errorMessage ?? "Something went wrong."}
				</p>
			)}
		</form>
	);
}
