// packages/vue/src/nodes/ImageNode.vue
<script setup lang="ts">
import {
	hoverEffectClass,
	hoverGlowStyle,
	IMAGE_SRCSET_WIDTHS,
	RADIUS,
	resolveShadow,
} from "@kivcode/nodes";
import { computed, inject } from "vue";
import { KIV_MEDIA_KEY } from "../media";

const props = defineProps<{
	src?: string;
	alt?: string;
	fit?: string;
	aspectRatio?: string;
	width?: string;
	height?: string;
	borderRadius?: string;
	shadow?: string;
	shadowColor?: string;
	clipPath?: string;
	hoverEffect?: string;
	hoverGlowColor?: string;
}>();

const media = inject(KIV_MEDIA_KEY, null);

// Without a MediaProvider, resolve() is the identity and no srcset is
// generated — a raw URL string has no reliable way to derive width variants.
const resolvedSrc = computed(
	() => media?.resolve(props.src ?? "", {}) ?? props.src ?? "",
);

const srcset = computed(() => {
	if (!media || !props.src) return undefined;
	return IMAGE_SRCSET_WIDTHS.map(
		(w) => `${media.resolve(props.src ?? "", { width: w })} ${w}w`,
	).join(", ");
});

const imageStyle = computed(() => ({
	objectFit: (props.fit ?? "cover") as "cover" | "contain" | "fill" | "none",
	aspectRatio: props.aspectRatio !== "auto" ? props.aspectRatio : undefined,
	width: props.width ?? "100%",
	height: props.height || undefined,
	maxWidth: "100%",
	display: "block",
	borderRadius: RADIUS[props.borderRadius ?? "none"] ?? "0",
	boxShadow: resolveShadow(
		props.shadow ?? "none",
		props.shadowColor || undefined,
	),
	clipPath: props.clipPath || undefined,
	...hoverGlowStyle(props.hoverGlowColor),
}));
const hoverClass = computed(() => hoverEffectClass(props.hoverEffect));
</script>

<template>
	<img
		:src="resolvedSrc"
		:srcset="srcset"
		sizes="100vw"
		loading="lazy"
		:alt="alt ?? ''"
		:class="hoverClass"
		:style="imageStyle"
		data-kiv-type="image"
	/>
</template>

// packages/react/src/nodes/ImageNode.tsx
import {
	hoverEffectClass,
	hoverGlowStyle,
	IMAGE_SRCSET_WIDTHS,
	RADIUS,
	resolveShadow,
} from "@kivcode/nodes";
import { useContext, useMemo } from "react";
import { KivMediaContext } from "../media";
import type { KivNodeComponentProps } from "../node-props";

export interface ImageNodeProps extends KivNodeComponentProps {
	src?: string;
	alt?: string;
	fit?: string;
	aspectRatio?: string;
	width?: string;
	height?: string;
	borderRadius?: string;
	shadow?: string;
	shadowColor?: string;
	clipPath?: string;
	hoverEffect?: string;
	hoverGlowColor?: string;
}

export function ImageNode({
	src,
	alt,
	fit,
	aspectRatio,
	width,
	height,
	borderRadius,
	shadow,
	shadowColor,
	clipPath,
	hoverEffect,
	hoverGlowColor,
	id,
	style,
	...rest
}: ImageNodeProps) {
	const media = useContext(KivMediaContext);

	// Without a MediaProvider, resolve() is the identity and no srcset is
	// generated — a raw URL string has no reliable way to derive width variants.
	const resolvedSrc = media?.resolve(src ?? "", {}) ?? src ?? "";

	const srcSet = useMemo(() => {
		if (!media || !src) return undefined;
		return IMAGE_SRCSET_WIDTHS.map(
			(w) => `${media.resolve(src ?? "", { width: w })} ${w}w`,
		).join(", ");
	}, [media, src]);

	const imageStyle = useMemo(
		() => ({
			objectFit: (fit ?? "cover") as "cover" | "contain" | "fill" | "none",
			aspectRatio: aspectRatio !== "auto" ? aspectRatio : undefined,
			width: width ?? "100%",
			height: height || undefined,
			maxWidth: "100%",
			display: "block",
			borderRadius: RADIUS[borderRadius ?? "none"] ?? "0",
			boxShadow: resolveShadow(shadow ?? "none", shadowColor || undefined),
			clipPath: clipPath || undefined,
			...hoverGlowStyle(hoverGlowColor),
			...style,
		}),
		[
			fit,
			aspectRatio,
			width,
			height,
			borderRadius,
			shadow,
			shadowColor,
			clipPath,
			hoverGlowColor,
			style,
		],
	);
	const hoverClass = hoverEffectClass(hoverEffect);

	return (
		<img
			id={id}
			src={resolvedSrc}
			srcSet={srcSet}
			sizes="100vw"
			loading="lazy"
			alt={alt ?? ""}
			className={hoverClass}
			style={imageStyle}
			data-kiv-type="image"
			{...rest}
		/>
	);
}
