// packages/vue/src/nodes/ZStackNode.vue
<script setup lang="ts">
import { zStackStyle } from "@kivcode/nodes";
import { computed } from "vue";

const props = defineProps<{
	minHeight?: string;
	overflow?: string;
}>();

// Style comes from the shared resolver, so this component and the static HTML
// export can never drift apart.
const style = computed(() => zStackStyle({ ...props }));
</script>

<template>
	<div :style="style" data-kiv-type="z-stack">
		<slot />
	</div>
</template>

// packages/react/src/nodes/ZStackNode.tsx
import { zStackStyle } from "@kivcode/nodes";
import { useMemo } from "react";
import type { KivNodeComponentProps } from "../node-props";

export interface ZStackNodeProps extends KivNodeComponentProps {
	minHeight?: string;
	overflow?: string;
}

export function ZStackNode({
	minHeight,
	overflow,
	slots,
	id,
	style,
	...rest
}: ZStackNodeProps) {
	const resolved = useMemo(
		() => ({ ...zStackStyle({ minHeight, overflow }), ...style }),
		[minHeight, overflow, style],
	);

	return (
		<div id={id} style={resolved} data-kiv-type="z-stack" {...rest}>
			{slots?.default}
		</div>
	);
}
