// packages/vue-editor/src/inspector/controls/PricingEditor.vue
<script setup lang="ts">
import type { LinkType, PricingData } from "@kivcode/nodes";
import { computed } from "vue";

const props = defineProps<{
	modelValue?: string;
}>();

const emit = defineEmits<{
	"update:modelValue": [value: string];
}>();

const LINK_TYPES = ["none", "internal", "external", "anchor"] as const;

function parse(v: string | undefined): PricingData {
	if (!v)
		return {
			tiers: [{ period: "", tier: "", highlighted: false }],
			rows: [{ label: "", values: [""] }],
		};
	try {
		const p = JSON.parse(v);
		// `ctaLinkType`/`ctaHref` stay `undefined` when the tier never set its
		// own link — not defaulted to "none" here, or re-saving any OTHER
		// tier's edit would bake "none" into every tier that was never
		// touched, permanently overriding the shared link's fallback for them.
		const tiers = Array.isArray(p?.tiers)
			? p.tiers.map((t: Record<string, unknown>) => ({
					period: String(t?.period ?? ""),
					tier: String(t?.tier ?? ""),
					highlighted: Boolean(t?.highlighted),
					ctaLinkType:
						typeof t?.ctaLinkType === "string"
							? (t.ctaLinkType as LinkType)
							: undefined,
					ctaHref: typeof t?.ctaHref === "string" ? t.ctaHref : undefined,
				}))
			: [{ period: "", tier: "", highlighted: false }];
		const rows = Array.isArray(p?.rows)
			? p.rows.map((r: Record<string, unknown>) => ({
					label: String(r?.label ?? ""),
					values: Array.isArray(r?.values) ? r.values.map(String) : [""],
				}))
			: [{ label: "", values: [""] }];
		return { tiers, rows };
	} catch {
		return {
			tiers: [{ period: "", tier: "", highlighted: false }],
			rows: [{ label: "", values: [""] }],
		};
	}
}

const data = computed(() => parse(props.modelValue));

function serialize(d: PricingData): string {
	return JSON.stringify(d);
}

function updateTier(
	index: number,
	patch: Partial<PricingData["tiers"][number]>,
): void {
	const tiers = data.value.tiers.map((t, i) =>
		i === index ? { ...t, ...patch } : t,
	);
	emit("update:modelValue", serialize({ ...data.value, tiers }));
}

function updateRowLabel(index: number, label: string): void {
	const rows = data.value.rows.map((r, i) =>
		i === index ? { ...r, label } : r,
	);
	emit("update:modelValue", serialize({ ...data.value, rows }));
}

function updateCell(rowIdx: number, tierIdx: number, value: string): void {
	const rows = data.value.rows.map((r, i) => {
		if (i !== rowIdx) return r;
		const values = [...r.values];
		values[tierIdx] = value;
		return { ...r, values };
	});
	emit("update:modelValue", serialize({ ...data.value, rows }));
}

function updateTierLinkType(index: number, value: string): void {
	updateTier(index, { ctaLinkType: value as LinkType });
}

function addTier(): void {
	const tiers = [
		...data.value.tiers,
		{ period: "", tier: "", highlighted: false },
	];
	const rows = data.value.rows.map((r) => ({
		...r,
		values: [...r.values, ""],
	}));
	emit("update:modelValue", serialize({ tiers, rows }));
}

function removeTier(index: number): void {
	if (data.value.tiers.length <= 1) return;
	const tiers = data.value.tiers.filter((_, i) => i !== index);
	const rows = data.value.rows.map((r) => ({
		...r,
		values: r.values.filter((_, i) => i !== index),
	}));
	emit("update:modelValue", serialize({ tiers, rows }));
}

function addRow(): void {
	const rows = [
		...data.value.rows,
		{ label: "", values: data.value.tiers.map(() => "") },
	];
	emit("update:modelValue", serialize({ ...data.value, rows }));
}

function removeRow(index: number): void {
	const rows = data.value.rows.filter((_, i) => i !== index);
	emit(
		"update:modelValue",
		serialize({
			...data.value,
			rows: rows.length
				? rows
				: [{ label: "", values: data.value.tiers.map(() => "") }],
		}),
	);
}
</script>

<template>
	<div class="kiv-pricing-editor">
		<div class="kiv-pricing-editor__toolbar">
			<button type="button" class="kiv-pricing-editor__btn" @click="addTier">+ Tier</button>
			<button type="button" class="kiv-pricing-editor__btn" @click="addRow">+ Row</button>
		</div>
		<div class="kiv-pricing-editor__grid">
			<table>
				<thead>
					<tr>
						<th class="kiv-pricing-editor__cell kiv-pricing-editor__cell--actions"></th>
						<th
							v-for="(tier, ti) in data.tiers"
							:key="'tier' + ti"
							class="kiv-pricing-editor__cell kiv-pricing-editor__cell--header"
						>
							<input
								:value="tier.period"
								class="kiv-pricing-editor__input"
								placeholder="Period"
								@input="updateTier(ti, { period: ($event.target as HTMLInputElement).value })"
							/>
							<input
								:value="tier.tier"
								class="kiv-pricing-editor__input kiv-pricing-editor__input--strong"
								placeholder="Tier"
								@input="updateTier(ti, { tier: ($event.target as HTMLInputElement).value })"
							/>
							<label class="kiv-pricing-editor__highlight">
								<input
									type="checkbox"
									:checked="tier.highlighted"
									@change="updateTier(ti, { highlighted: ($event.target as HTMLInputElement).checked })"
								/>
								Highlight
							</label>
							<select
								class="kiv-pricing-editor__input kiv-pricing-editor__select"
								:value="tier.ctaLinkType ?? 'none'"
								title="This tier's own CTA link — overrides the shared one below when set"
								@change="updateTierLinkType(ti, ($event.target as HTMLSelectElement).value)"
							>
								<option v-for="lt in LINK_TYPES" :key="lt" :value="lt">{{ lt }}</option>
							</select>
							<input
								v-if="tier.ctaLinkType && tier.ctaLinkType !== 'none'"
								:value="tier.ctaHref"
								class="kiv-pricing-editor__input"
								placeholder="/path, https://…, or #section-id"
								@input="updateTier(ti, { ctaHref: ($event.target as HTMLInputElement).value })"
							/>
							<button
								v-if="data.tiers.length > 1"
								type="button"
								class="kiv-pricing-editor__remove"
								title="Remove tier"
								@click="removeTier(ti)"
							>&times;</button>
						</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="(row, ri) in data.rows" :key="'row' + ri">
						<td class="kiv-pricing-editor__cell">
							<input
								:value="row.label"
								class="kiv-pricing-editor__input"
								placeholder="Row label"
								@input="updateRowLabel(ri, ($event.target as HTMLInputElement).value)"
							/>
						</td>
						<td
							v-for="(tier, ti) in data.tiers"
							:key="'cell' + ri + '-' + ti"
							class="kiv-pricing-editor__cell"
						>
							<input
								:value="row.values[ti] ?? ''"
								class="kiv-pricing-editor__input"
								placeholder="Value"
								@input="updateCell(ri, ti, ($event.target as HTMLInputElement).value)"
							/>
						</td>
						<td class="kiv-pricing-editor__cell kiv-pricing-editor__cell--actions">
							<button
								type="button"
								class="kiv-pricing-editor__remove"
								title="Remove row"
								@click="removeRow(ri)"
							>&times;</button>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</template>

<style scoped>
.kiv-pricing-editor {
	display: flex;
	flex-direction: column;
	gap: 8px;
}
.kiv-pricing-editor__toolbar {
	display: flex;
	gap: 6px;
}
.kiv-pricing-editor__btn {
	padding: 4px 10px;
	border: 1px solid var(--color-border);
	border-radius: 6px;
	background: var(--color-surface-sunken);
	color: var(--color-text-secondary);
	font-size: 0.75rem;
	cursor: pointer;
}
.kiv-pricing-editor__grid {
	max-height: 320px;
	overflow: auto;
	border: 1px solid var(--color-border);
	border-radius: 6px;
}
.kiv-pricing-editor__grid table {
	width: 100%;
	border-collapse: collapse;
}
.kiv-pricing-editor__cell {
	position: relative;
	padding: 4px;
	border: 1px solid var(--color-border);
	vertical-align: top;
	min-width: 90px;
}
.kiv-pricing-editor__cell--header {
	background: var(--color-surface-overlay);
}
.kiv-pricing-editor__cell--actions {
	width: 24px;
	padding: 0;
	text-align: center;
	border: none;
	background: transparent;
}
.kiv-pricing-editor__input {
	width: 100%;
	padding: 3px 5px;
	border: none;
	background: transparent;
	color: var(--color-text-primary);
	font-size: 0.78rem;
	outline: none;
	display: block;
}
.kiv-pricing-editor__input--strong {
	font-weight: 700;
}
.kiv-pricing-editor__select {
	cursor: pointer;
}
.kiv-pricing-editor__input:focus {
	background: var(--color-accent-muted);
	border-radius: 3px;
}
.kiv-pricing-editor__highlight {
	display: flex;
	align-items: center;
	gap: 4px;
	font-size: 0.68rem;
	color: var(--color-text-muted);
	padding: 2px 4px;
}
.kiv-pricing-editor__remove {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	width: 18px;
	height: 18px;
	border: none;
	border-radius: 4px;
	background: transparent;
	color: var(--color-text-muted);
	font-size: 0.85rem;
	cursor: pointer;
}
.kiv-pricing-editor__remove:hover {
	color: #ef4444;
}
</style>

// packages/react-editor/src/inspector/controls/PricingEditor.tsx
import type { FieldDescriptor } from "@kivcode/engine";
import type { LinkType, PricingData } from "@kivcode/nodes";
import { useMemo } from "react";

export interface PricingEditorProps {
	value?: string;
	/** Part of the common plugin-control contract; unused here (same as the Vue original, which never declared it either). */
	fieldKey?: string;
	descriptor?: FieldDescriptor;
	onChange: (value: string) => void;
}

const LINK_TYPES: LinkType[] = ["none", "internal", "external", "anchor"];

function parse(v: string | undefined): PricingData {
	if (!v)
		return {
			tiers: [{ period: "", tier: "", highlighted: false }],
			rows: [{ label: "", values: [""] }],
		};
	try {
		const p = JSON.parse(v);
		// `ctaLinkType`/`ctaHref` stay `undefined` when the tier never set its
		// own link — not defaulted to "none" here, or re-saving any OTHER
		// tier's edit would bake "none" into every tier that was never
		// touched, permanently overriding the shared link's fallback for them.
		const tiers = Array.isArray(p?.tiers)
			? p.tiers.map((t: Record<string, unknown>) => ({
					period: String(t?.period ?? ""),
					tier: String(t?.tier ?? ""),
					highlighted: Boolean(t?.highlighted),
					ctaLinkType:
						typeof t?.ctaLinkType === "string"
							? (t.ctaLinkType as LinkType)
							: undefined,
					ctaHref: typeof t?.ctaHref === "string" ? t.ctaHref : undefined,
				}))
			: [{ period: "", tier: "", highlighted: false }];
		const rows = Array.isArray(p?.rows)
			? p.rows.map((r: Record<string, unknown>) => ({
					label: String(r?.label ?? ""),
					values: Array.isArray(r?.values) ? r.values.map(String) : [""],
				}))
			: [{ label: "", values: [""] }];
		return { tiers, rows };
	} catch {
		return {
			tiers: [{ period: "", tier: "", highlighted: false }],
			rows: [{ label: "", values: [""] }],
		};
	}
}

function serialize(d: PricingData): string {
	return JSON.stringify(d);
}

export function PricingEditor({
	value,
	fieldKey: _fieldKey,
	descriptor: _descriptor,
	onChange,
}: PricingEditorProps) {
	const data = useMemo(() => parse(value), [value]);

	function updateTier(
		index: number,
		patch: Partial<PricingData["tiers"][number]>,
	): void {
		const tiers = data.tiers.map((t, i) =>
			i === index ? { ...t, ...patch } : t,
		);
		onChange(serialize({ ...data, tiers }));
	}

	function updateRowLabel(index: number, label: string): void {
		const rows = data.rows.map((r, i) => (i === index ? { ...r, label } : r));
		onChange(serialize({ ...data, rows }));
	}

	function updateCell(
		rowIdx: number,
		tierIdx: number,
		cellValue: string,
	): void {
		const rows = data.rows.map((r, i) => {
			if (i !== rowIdx) return r;
			const values = [...r.values];
			values[tierIdx] = cellValue;
			return { ...r, values };
		});
		onChange(serialize({ ...data, rows }));
	}

	function updateTierLinkType(index: number, value: string): void {
		updateTier(index, { ctaLinkType: value as LinkType });
	}

	function addTier(): void {
		const tiers = [...data.tiers, { period: "", tier: "", highlighted: false }];
		const rows = data.rows.map((r) => ({ ...r, values: [...r.values, ""] }));
		onChange(serialize({ tiers, rows }));
	}

	function removeTier(index: number): void {
		if (data.tiers.length <= 1) return;
		const tiers = data.tiers.filter((_, i) => i !== index);
		const rows = data.rows.map((r) => ({
			...r,
			values: r.values.filter((_, i) => i !== index),
		}));
		onChange(serialize({ tiers, rows }));
	}

	function addRow(): void {
		const rows = [
			...data.rows,
			{ label: "", values: data.tiers.map(() => "") },
		];
		onChange(serialize({ ...data, rows }));
	}

	function removeRow(index: number): void {
		const rows = data.rows.filter((_, i) => i !== index);
		onChange(
			serialize({
				...data,
				rows: rows.length
					? rows
					: [{ label: "", values: data.tiers.map(() => "") }],
			}),
		);
	}

	return (
		<div className="kiv-pricing-editor">
			<div className="kiv-pricing-editor__toolbar">
				<button
					type="button"
					className="kiv-pricing-editor__btn"
					onClick={addTier}
				>
					+ Tier
				</button>
				<button
					type="button"
					className="kiv-pricing-editor__btn"
					onClick={addRow}
				>
					+ Row
				</button>
			</div>
			<div className="kiv-pricing-editor__grid">
				<table>
					<thead>
						<tr>
							<th className="kiv-pricing-editor__cell kiv-pricing-editor__cell--actions" />
							{data.tiers.map((tier, ti) => (
								<th
									// biome-ignore lint/suspicious/noArrayIndexKey: tiers have no stable id — same positional keying as the Vue original's `:key="'tier' + ti"`
									key={`tier-${ti}`}
									className="kiv-pricing-editor__cell kiv-pricing-editor__cell--header"
								>
									<input
										value={tier.period}
										className="kiv-pricing-editor__input"
										placeholder="Period"
										onChange={(e) => updateTier(ti, { period: e.target.value })}
									/>
									<input
										value={tier.tier}
										className="kiv-pricing-editor__input kiv-pricing-editor__input--strong"
										placeholder="Tier"
										onChange={(e) => updateTier(ti, { tier: e.target.value })}
									/>
									<label className="kiv-pricing-editor__highlight">
										<input
											type="checkbox"
											checked={tier.highlighted}
											onChange={(e) =>
												updateTier(ti, { highlighted: e.target.checked })
											}
										/>
										Highlight
									</label>
									<select
										className="kiv-pricing-editor__input kiv-pricing-editor__select"
										value={tier.ctaLinkType ?? "none"}
										title="This tier's own CTA link — overrides the shared one below when set"
										onChange={(e) => updateTierLinkType(ti, e.target.value)}
									>
										{LINK_TYPES.map((lt) => (
											<option key={lt} value={lt}>
												{lt}
											</option>
										))}
									</select>
									{tier.ctaLinkType && tier.ctaLinkType !== "none" && (
										<input
											value={tier.ctaHref ?? ""}
											className="kiv-pricing-editor__input"
											placeholder="/path, https://…, or #section-id"
											onChange={(e) =>
												updateTier(ti, { ctaHref: e.target.value })
											}
										/>
									)}
									{data.tiers.length > 1 && (
										<button
											type="button"
											className="kiv-pricing-editor__remove"
											title="Remove tier"
											onClick={() => removeTier(ti)}
										>
											&times;
										</button>
									)}
								</th>
							))}
						</tr>
					</thead>
					<tbody>
						{data.rows.map((row, ri) => (
							// biome-ignore lint/suspicious/noArrayIndexKey: rows have no stable id — same positional keying as the Vue original's `:key="'row' + ri"`
							<tr key={`row-${ri}`}>
								<td className="kiv-pricing-editor__cell">
									<input
										value={row.label}
										className="kiv-pricing-editor__input"
										placeholder="Row label"
										onChange={(e) => updateRowLabel(ri, e.target.value)}
									/>
								</td>
								{data.tiers.map((_tier, ti) => (
									<td
										// biome-ignore lint/suspicious/noArrayIndexKey: cells have no stable id — same positional keying as the Vue original's `:key="'cell' + ri + '-' + ti"`
										key={`cell-${ri}-${ti}`}
										className="kiv-pricing-editor__cell"
									>
										<input
											value={row.values[ti] ?? ""}
											className="kiv-pricing-editor__input"
											placeholder="Value"
											onChange={(e) => updateCell(ri, ti, e.target.value)}
										/>
									</td>
								))}
								<td className="kiv-pricing-editor__cell kiv-pricing-editor__cell--actions">
									<button
										type="button"
										className="kiv-pricing-editor__remove"
										title="Remove row"
										onClick={() => removeRow(ri)}
									>
										&times;
									</button>
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</div>
		</div>
	);
}
